//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment_table
    {
        public int comment_id { get; set; }
        public int visitor_id { get; set; }
        public int article_id { get; set; }
        public string comment_body { get; set; }
    
        public virtual article_table article_table { get; set; }
        public virtual visitor_table visitor_table { get; set; }
    }
}
