//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloggingEntities : DbContext
    {
        public BloggingEntities()
            : base("name=BloggingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin_table> admin_table { get; set; }
        public virtual DbSet<article_table> article_table { get; set; }
        public virtual DbSet<category_table> category_table { get; set; }
        public virtual DbSet<comment_table> comment_table { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<visitor_table> visitor_table { get; set; }
    }
}
